app/models.py
from app import db


class Blog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titel = db.Column(db.String(50), nullable=False)
    kategorie_id = db.Column(db.Integer, db.ForeignKey('kategorie.id'), nullable=False)
    text = db.Column(db.String(9999))

class Kategorie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    blog = db.relationship('Blog', lazy='select', backref=db.backref('Kategorie', lazy='joined'))

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config

db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    from app.error import bp as error_bp
    app.register_blueprint(error_bp)

    from app.blog import bp as blog_bp
    app.register_blueprint(blog_bp)

    from app.kategorie import bp as kategorie_bp
    app.register_blueprint(kategorie_bp)

    from app.admin import bp as admin_bp
    app.register_blueprint(admin_bp)

    return app


from app import models

app/admin/__init__.py
from flask import Blueprint

bp = Blueprint('admin', __name__)

from app.admin import routes

app/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__)

from app.blog import routes

app/blog/routes.py
import datetime
import os

from flask import render_template, request, redirect, url_for, flash, app
from app import db
from app.blog import bp
from app.blog.form import Blogform
from app.models import Blog, Kategorie


@bp.route('/')
def index():
    return render_template('blog/index.html', items=Blog.query.limit(3).all())

@bp.route('/blog/blogs')
def blogs():
    return render_template('blog/blogs.html', items=Blog.query.all())

@bp.route('/blog/entries/<int:id>')
def entries(id):
    blog = Blog.query.filter_by(kategorie_id=id)
    flash("Diese Kateogire enthält folgende Blogeinträge.")
    return render_template('blog/entries.html', items=blog)


@bp.route('/blog/detail/<int:id>')
def blog_detail(id):
    blog = Blog.query.get_or_404(id)
    return render_template('blog/blog.html', blog=blog)


@bp.route('/blog/remove/<int:id>')
def blog_remove(id):
    blog = Blog.query.get_or_404(id)
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for('blog.index'))

@bp.route('/blog/erstellen')
def blog_erstellen():
    form = Blogform(request.form)
    kategorie = Kategorie.query.all()
    return render_template('blog/erstellen.html', form=form, kategorie=kategorie)


@bp.route('/blog/erstellen', methods=['POST'])
def blog_erstellen_post():
    flash("Blog-Eintrag wurde erstellt.")
    form = Blogform(request.form)
    if form.validate():
        blog = Blog()
        blog.titel = form.blogtitel.data
        blog.kategorie_id = form.kategorie.data
        blog.text = form.text.data
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('blog.blogs'))
    return render_template('blog/blogs.html', form=form)

@bp.route('/blog/update/<int:id>')
def blog_update_get(id):
    flash("Blog-Eintrag wurde geladen.")
    blog = Blog.query.get_or_404(id)
    form = Blogform(request.form)
    form.blogtitel.data = blog.titel
    form.kategorie.data = blog.kategorie_id
    form.text.data = blog.text
    return render_template('blog/update_blog.html', form=form, kategorie=Kategorie.query.all())


@bp.route('/blog/update/<int:id>', methods=['POST'])
def blog_update_post(id):
    flash("Blog-Eintrag wurde aktualisiert.")
    form = Blogform(request.form)
    if form.validate():
        blog = Blog.query.get_or_404(id)
        blog.titel = form.blogtitel.data
        blog.kategorie_id = form.kategorie.data
        blog.text = form.text.data
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('blog.blog_detail', id=blog.id))
    return render_template('blog/update_blog.html', form=form,  kategorie=Kategorie.query.all())

app/kategorie/__init__.py
from flask import Blueprint

bp = Blueprint('kategorie', __name__)

from app.kategorie import routes

app/kategorie/routes.py
import datetime
import os

from flask import render_template, request, redirect, url_for, flash, app
from app import db
from app.kategorie import bp
from app.blog.form import Blogform
from app.kategorie.form import Kategorieform
from app.models import Blog, Kategorie


@bp.route('/kategorie/overview')
def kategorie():
    return render_template('kategorie/uebersicht.html', items=Kategorie.query.all())


@bp.route('/kategorie/detail/<int:id>')
def kategorie_detail(id):
    kategorie = Kategorie.query.get_or_404(id)
    return render_template('kategorie/kategorie.html', kategorie=kategorie)


@bp.route('/kategorie/remove/<int:id>')
def kategorie_remove(id):
    flash("Kategorie wurde gelöscht.")
    kategorie = Kategorie.query.get_or_404(id)
    db.session.delete(kategorie)
    db.session.commit()
    return render_template('kategorie/uebersicht.html', items=Kategorie.query.all())

@bp.route('/kategorie/create')
def kategorie_create():
    form = Kategorieform(request.form)
    return render_template('kategorie/erstellen.html', form=form)


@bp.route('/kategorie/create', methods=['POST'])
def kategorie_create_post():
    flash("Kategorie wurde erstellt.")
    form = Kategorieform(request.form)
    if form.validate():
        kategorie = Kategorie()
        kategorie.name = form.name.data
        db.session.add(kategorie)
        db.session.commit()
        return redirect(url_for('kategorie.kategorie'))
    return render_template('kategorie/erstellen.html', form=form)

@bp.route('/kategorie/update/<int:id>')
def kategorie_update_get(id):
    flash("Die Kategorie wurde geladen.")
    kategorie = Kategorie.query.get_or_404(id)
    form = Kategorieform(request.form)
    form.kategorie.data = kategorie.name
    return render_template('kategorie/update_kategorie.html', form=form, kategorie=Kategorie.query.all())



@bp.route('/kategorie/update/<int:id>', methods=['POST'])
def kategorie_update_post(id):
    flash("Kategoriename wurde aktualisiert.")
    form = Kategorieform(request.form)
    if form.validate():
        kategorie = Kategorie.query.get_or_404(id)
        kategorie.name = form.kategorie.data
        db.session.add(kategorie)
        db.session.commit()
        return redirect(url_for('kategorie.kategorie_detail', id=kategorie.id))
    return render_template('kategorie/update_kategorie.html', form=form, kategorie=Kategorie.query.all())

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">MyBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Blog
                </a>
                <div class="dropdown-menu  " aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('blog.blogs') }}">Uebersicht</a>
                    <a class="dropdown-item" href="{{ url_for('blog.blog_erstellen') }}">Erstellen</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Kategorien
                </a>
                <div class="dropdown-menu  " aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('kategorie.kategorie') }}">Uebersicht</a>
                    <a class="dropdown-item" href="{{ url_for('kategorie.kategorie_create') }}">Erstellen</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>


        </ul>
        <form action="/search" method="POST" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search_string"
                   aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Suchen</button>
        </form>
    </div>
</nav>


<div class="mt-3 mb-3">
    <div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <p class="alert alert-info">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </p>
    {% endif %}
{% endwith %}
        <div class="card mb-5">

            {% block content %}{% endblock %}
        </div>


    </div>
</div>

<footer class="footer-distributed">

    <div class="">

        <p class="text-center text-light">MyBlog &copy; 2020</p>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/blog/blog.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    <div class="card shadow">
        <div class="card-body">
            <p>
            <h1>{{ blog.titel }}</h1>
            </p>
            <p>
            <h4>Kategorie: {{ blog.Kategorie.name }}</h4>
            </p>
            <p>
                {{ blog.text }}
            </p>
            <a class="btn btn-danger" href="{{ url_for('blog.blog_remove',id=item.id) }}">Remove</a>
            <a class="btn btn-primary" href="{{ url_for('blog.blog_update_get',id=blog.id) }}">Update</a>
            <a class="btn btn-primary" href="{{ url_for('blog.blogs') }}">Back</a>
        </div>
    </div>
{% endblock %}

app/templates/blog/blogs.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    {% for item in items %}
        <div class="card">
            <h5 class="card-header">
                <a href="{{ url_for('blog.entries', id=item.Kategorie.id) }}">{{ item.Kategorie.name }}
                </a>
            </h5>
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{{ url_for('blog.blog_detail', id=item.id) }}">{{ item.titel }}
                    </a>
                </h5>
                <a href="{{ url_for('blog.blog_detail', id=item.id) }}" class="btn btn-primary">
                    Weiterlesen
                </a>
                <a class="btn btn-danger" href="{{ url_for('blog.blog_remove',id=item.id) }}">Remove</a>
                <a class="btn btn-primary" href="{{ url_for('blog.blog_update_get',id=item.id) }}">Update</a>
                <a class="btn btn-primary" href="{{ url_for('blog.blogs') }}">Back</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

app/templates/blog/entries.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}


        </div>
        {% for item in items %}
            <div class="card">
                <h5 class="card-header">
                    <a href="{{ url_for('blog.entries', id=item.Kategorie.id) }}">{{ item.Kategorie.name }}
                    </a>
                </h5>
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ url_for('blog.blog_detail', id=item.id) }}">{{ item.titel }}
                        </a>
                    </h5>
                    <a href="{{ url_for('blog.blog_detail', id=item.id) }}" class="btn btn-primary">Weiterlesen
                    </a>
                    <a class="btn btn-danger" href="{{ url_for('blog.blog_remove',id=item.id) }}">Remove</a>
                    <a class="btn btn-primary" href="{{ url_for('blog.blog_update_get',id=item.id) }}">Update</a>
                    <a class="btn btn-primary" href="{{ url_for('blog.blogs') }}">Back</a>
                </div>
            </div>
        {% endfor %}
{% endblock %}

app/templates/blog/erstellen.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    <div class="card shadow">
        <div class="card-body">
            <form method="post" action="" role="form" novalidate>
                {{ form.csrf }}
                <div class="form-group">
                    <label for="Blogtitel">{{ form.blogtitel.label.text }}</label>
                    <input name="blogtitel" type="text" class="form-control" id="Blogtitel"
                           value="{{ form.blogtitel.data }}">
                </div>

                <div class="form-group">
                    <label for="Kategorie">{{ form.kategorie.label.text }}</label>
                    <select class="form-control" id="kategorie" name="kategorie">
                        {% for k in kategorie %}
                            <option value="{{ k.id }}">{{ k.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="Text">{{ form.text.label.text }}</label>
                    <textarea name="text" type="text" class="form-control" id="Text"
                              value="{{ form.text.data }}"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>

{% endblock %}

app/templates/blog/index.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    {% for item in items %}
        <div class="card">
            <h5 class="card-header">
                <a href="{{ url_for('blog.entries', id=item.Kategorie.id) }}">{{ item.Kategorie.name }}
                </a>
            </h5>
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{{ url_for('blog.blog_detail', id=item.id) }}">{{ item.titel }}
                    </a>
                </h5>
                <a href="{{ url_for('blog.blog_detail', id=item.id) }}" class="btn btn-primary">Weiterlesen</a>

            </div>
        </div>
    {% endfor %}



{% endblock %}

app/templates/blog/update_blog.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    <div class="card shadow">
        <div class="card-body">
            <form method="post" action="" role="form" novalidate>
                {{ form.csrf }}
                <div class="form-group">
                    <label for="Blogtitel">{{ form.blogtitel.label.text }}</label>
                    <input name="blogtitel" type="text" class="form-control" id="Blogtitel"
                           value="{{ form.blogtitel.data }}">
                </div>

                <div class="form-group">
                    <label for="Kategorie">{{ form.kategorie.label.text }}</label>
                    <select class="form-control" id="kategorie" name="kategorie">
                        {% for k in kategorie %}
                            <option value="{{ k.id }}" {% if form.kategorie.data == k.id %} selected="selected" {% endif %}>{{ k.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="Text">{{ form.text.label.text }}</label>
                    <textarea name="text" type="text" class="form-control" id="Text">{{ form.text.data }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/kategorie/erstellen.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    <div class="card shadow">
        <div class="card-body">
            <form method="post" action="" role="form" novalidate>
                {{ form.csrf }}

                <div class="form-group">
                    <label for="Kategorie">{{ form.name.label.text }}</label>
                    <input name="name" type="text" class="form-control" id="Kategorie" value="{{ form.name.data }}">
                </div>

                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>

{% endblock %}

app/templates/kategorie/kategorie.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    <div class="card">
        <h5 class="card-header">
            <a href="{{ url_for('blog.entries', id=item.Kategorie.id) }}">{{ item.Kategorie.name }}
            </a>
        </h5>
        <div class="card-body">
                            <h5 class="card-title">
                    <a href="{{ url_for('blog.blog_detail', id=item.id) }}">{{ item.titel }}
                    </a>
                </h5>
            <a class="btn btn-danger" href="{{ url_for('kategorie.kategorie_remove',id=item.id) }}">Remove</a>
            <a class="btn btn-primary" href="{{ url_for('kategorie.kategorie_update_get',id=item.id) }}">Update</a>
            <a class="btn btn-primary" href="{{ url_for('kategorie.kategorie') }}">Back</a>
        </div>
    </div>
{% endblock %}

app/templates/kategorie/kategorien.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}


    <div class="card shadow">
        <div class="card-body">
            <ul class="list-group">
                {% for item in items %}
                    <a href="{{ url_for('blog.kategorie', id=item.id) }}"> <li class="list-group-item">{{ item.name }}</li></a>
                {% endfor %}
            </ul>
        </div>
    </div>

        <div class="card shadow">
        <div class="card-body">
            <p>
                {{ kategorie.titel }}
            </p>
            <a class="btn btn-danger" href="{{ url_for('kategorie.remove',id=kategorie.id) }}">Remove</a>
            <a class="btn btn-primary" href="{{ url_for('kategorie.update_get',id=kategorie.id) }}">Update</a>
            <a class="btn btn-primary" href="{{ url_for('kategorie.kategorie') }}">Back</a>
        </div>
    </div>

{% endblock %}

app/templates/kategorie/uebersicht.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    {% for item in items %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{{ url_for('blog.entries', id=item.id) }}">{{ item.name }} - {{ item.blog|length }}
                    </a>
                    <a class="btn btn-danger" href="{{ url_for('kategorie.kategorie_remove',id=item.id) }}">Remove</a>
                    <a class="btn btn-primary" href="{{ url_for('kategorie.kategorie_update_get',id=item.id) }}">Update</a>
                    <a class="btn btn-primary" href="{{ url_for('kategorie.kategorie') }}">Back</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

app/templates/kategorie/update_kategorie.html
{% extends "base.html" %}
{% block title %}MyBlog{% endblock %}
{% block content %}

    <div class="card shadow">
        <div class="card-body">
            <form method="post" action="" role="form" novalidate>
                {{ form.csrf }}

                <div class="form-group">
                    <label for="Kategorie">{{ form.name.label.text }}</label>
                    <input name="kategorie" type="text" class="form-control" id="Kategorie"
                           value="{{ form.name.data }}">
                </div>
                <button type="submit" class="btn btn-primary">Speichern</button>
            </form>
        </div>
    </div>
{% endblock %}